"""initial tables

Revision ID: 19f42d1db0dd
Revises: 
Create Date: 2026-06-07 14:31:27.281283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '19f42d1db0dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###